name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Test AWS connection
        run: aws sts get-caller-identity

      - name: Build with Gradle
        run: ./gradlew build

      - name: Get AWS Account ID
        run: echo "ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)" >> $GITHUB_ENV

      - name: Zip application
        run: zip -r application.zip .

      - name: Upload to S3
        run: aws s3 cp application.zip s3://elasticbeanstalk-us-east-1-$ACCOUNT_ID/application.zip

      - name: Create new application version
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name HogwartsAPI \
            --version-label v-${{ github.run_number }} \
            --source-bundle S3Bucket="elasticbeanstalk-us-east-1-$ACCOUNT_ID",S3Key="application.zip"

      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk update-environment \
            --environment-name HogwartsAPI-env \
            --version-label v-${{ github.run_number }}