name: Deploy Docker to Elastic Beanstalk

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2️⃣ Configurar Java
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      # 3️⃣ Permiso a gradlew (IMPORTANTE en Linux)
      - name: Give execute permission to gradlew
        run: chmod +x gradlew

      # 4️⃣ Build con Gradle
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 5️⃣ Login en GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 6️⃣ Nombre fijo válido para la imagen
      - name: Set Image Name
        run: echo "IMAGE_NAME=ghcr.io/solucha72-commits/hogwartsapi" >> $GITHUB_ENV

      # 7️⃣ Build y push Docker
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.run_number }}


      # 8️⃣ Generar docker-compose.yml para Elastic Beanstalk
      - name: Generate docker-compose.yml
        run: |
          echo "services:
            app:
              image: ${{ env.IMAGE_NAME }}:${{ github.run_number }}
              ports:
                - '80:8080' 
              restart: always" > docker-compose.yml
      # 9️⃣ Deploy a Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          region: us-east-1
          application_name: HogwartsAPI
          environment_name: HogwartsAPI-env
          version_label: "hogwarts-v-${{ github.run_number }}"
          deployment_package: docker-compose.yml